In [3]:
pip install numpy

  Using cached numpy-2.2.0-cp311-cp311-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.0-cp311-cp311-win_amd64.whl (12.9 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\kgluc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [21]:
import numpy as np
import random
class Map:
    def __init__(self, num:int):
        self.num = num
        self.board = np.zeros([num,num])
        self.x = 1
        self.o = 2
    def place_x(self, row:int, col:int):
        self.board[row, col] = self.x

    def place_o(self, row:int, col:int):
        self.board[row, col] = self.o

    def clean(self):
        self.board = np.zeros([num, num])

    def is_full(self):
        return not np.any(self.board == 0)

class Player:
    def __init__(self, name):
        self.name = name
    def choice(self):
        pass
class RealPlayer(Player):
    def choose(self):
        row = random.randint(0,2)
        col = random.randint(0,2)
        return row, col
class Game:
    def __init__(self, player1:Player, player2:Player):
        self.player1 = player1
        self.player2 = player2
        self.map = Map(3)
        self.turn = 0
    def next_turn(self):
        if self.turn < 9:
            if self.turn%2 == 0:
                while True:
                    row, col = self.player1.choose()
                    if self.map.board[row,col] == 0:
                        self.map.place_x(row, col) 
                        break
                        
            if self.turn%2 == 1:
                while True:
                    row, col = self.player2.choose()
                    if self.map.board[row, col] == 0:
                        self.map.place_o(row, col) 
                        break

            self.turn = self.turn + 1

    def check(self):
        i = 0
        while i < self.map.num:
            if (list(self.map.board[:,i]) == [1,1,1] or list(self.map.board[i,:]) == [1,1,1]):
                return "X won"
            if (list(self.map.board[:,i]) == [2,2,2] or list(self.map.board[i,:]) == [2,2,2]):
                return "O won"
            i = i+1

        if all(self.map.board[i, i] == 1 for i in range(self.map.num)):  # top-left to bottom-right
            return "X won"
        if all(self.map.board[i, i] == 2 for i in range(self.map.num)):  # top-left to bottom-right
            return "O won"
        if all(self.map.board[i, self.map.num - 1 - i] == 1 for i in range(self.map.num)):  # top-right to bottom-left
            return "X won"
        if all(self.map.board[i, self.map.num - 1 - i] == 2 for i in range(self.map.num)):  # top-right to bottom-left
            return "O won"
        
        if self.map.is_full():
            return "Draw"

In [27]:
p1 = RealPlayer("Tomuś")
p2 = RealPlayer("Robert")
game = Game(p1, p2)

i = 0   
while i <10:
    x1,y1 = p1.choose()
    x2,y2 = p2.choose()
    test.place_o(x1,y1)
    test.place_x(x2,y2)
    i = i+1
game = Game(p1,p2)
game.next_turn()
print(game.map.board)
game.next_turn()
print(game.map.board)
game.next_turn()
print(game.map.board)
game.next_turn()
print(game.map.board)
game.next_turn()
print(game.map.board)
game.next_turn()
print(game.map.board)
game.next_turn()
print(game.map.board)
game.next_turn()
print(game.map.board)
game.next_turn()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]
[[0. 2. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]
[[0. 2. 0.]
 [0. 0. 0.]
 [0. 1. 1.]]
[[0. 2. 2.]
 [0. 0. 0.]
 [0. 1. 1.]]
[[0. 2. 2.]
 [0. 0. 1.]
 [0. 1. 1.]]
[[0. 2. 2.]
 [0. 2. 1.]
 [0. 1. 1.]]
[[0. 2. 2.]
 [1. 2. 1.]
 [0. 1. 1.]]
[[2. 2. 2.]
 [1. 2. 1.]
 [0. 1. 1.]]


In [28]:
game.check()

'O won'